spring.application.name=market

server.port=4710

spring.datasource.url=jdbc:mariadb://localhost:3307/marketplace
spring.datasource.username=FeralHorse
spring.datasource.password=Rjvfh503064@

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=eRPz9mkCpXJZOTNP1FoykOIsgABwXGU65XPiuiYeQtsuHrkQyQjSprXaqIh5iG0YtwYJiWjk9IJ2BZuvjsg1jWGWXYj9o4iEztwO

server.servlet.context-path=/api/v1.0

spring.mail.host=smtp.mail.ru
spring.mail.port=587
spring.mail.username=admin@web-site.tech
spring.mail.password=v78KLMj5WwaVIcEoJvW2

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true