spring.application.name=marketplace

spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasourse.username=root
spring.datasourse.password=

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update